import type { Metadata } from "next";
import { Noto_Sans_Bengali} from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const notoSansBengali = Noto_Sans_Bengali({
  variable: "--font-noto-sans-bengali",
  subsets: [ "latin", "bengali"],
});

export const metadata: Metadata = {
  title: "Bazar-dor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${notoSansBengali.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        {children}
        <div>Footer</div>
        </body>
    </html>
  );
}
